# Generated by Django 2.0 on 2018-07-10 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('white', 'White'), ('red', 'Red'), ('black', 'Black'), ('blue', 'Blue'), ('yellow', 'Yellow')], max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tag.ProductColor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Extra Small', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL'), ('Double Large', 'XXL'), ('Triple Large', 'XXXL'), ('13 inch', "13 ''"), ('15 inch', "15 ''")], default='Small', max_length=100)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='tag', unique=True)),
                ('Brand', models.CharField(blank=True, max_length=250, null=True)),
                ('Type', models.CharField(choices=[('menclothes', 'MenClothes'), ('womenclothes', 'WomenClothes'), ('kidsclothes', 'KidsClothes'), ('electronics', 'Electronics'), ('home&lifestyle', 'Home&LifeStyle'), ('sports', 'Sports')], max_length=300)),
                ('SubType', models.CharField(choices=[('shoes', 'Shoes'), ('bags', 'Bags'), ('accessories', 'Accessories'), ('clothes', 'Clothes'), ('mobiles', 'Mobiles'), ('cameras', 'Cameras'), ('laptop', 'Laptop'), ('tv', 'TV'), ('washingMachines', 'WashingMachines')], max_length=300)),
                ('SubSubType', models.CharField(blank=True, choices=[('sneakers', 'Sneakers'), ('boots', 'Boots'), ('sandals', 'Sandals'), ('watches', 'Watches'), ('sunglasses', 'Sunglasses'), ('perfumes', 'Perfumes'), ('jewellery', 'Jewellery')], max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='productcolorsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tag.ProductSize'),
        ),
    ]
