# Generated by Django 2.0 on 2018-11-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('Brand', models.CharField(blank=True, max_length=250, null=True)),
                ('Type', models.CharField(choices=[('menclothes', 'MenClothes'), ('womenclothes', 'WomenClothes'), ('kidsclothes', 'KidsClothes'), ('electronics', 'Electronics'), ('home&lifestyle', 'Home&LifeStyle'), ('sports', 'Sports')], max_length=300)),
                ('SubType', models.CharField(choices=[('shoes', 'Shoes'), ('bags', 'Bags'), ('accessories', 'Accessories'), ('clothes', 'Clothes'), ('shirts', 'Shirts'), ('mobiles', 'Mobiles'), ('cameras', 'Cameras'), ('laptop', 'Laptop'), ('tv', 'TV'), ('washingMachines', 'WashingMachines')], max_length=300)),
                ('SubSubType', models.CharField(blank=True, choices=[('sneakers', 'Sneakers'), ('boots', 'Boots'), ('sandals', 'Sandals'), ('watches', 'Watches'), ('sunglasses', 'Sunglasses'), ('perfumes', 'Perfumes'), ('jewellery', 'Jewellery')], max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
