# Generated by Django 2.0 on 2018-07-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
