# Generated by Django 2.0 on 2018-07-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0002_auto_20180710_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('red', 'Red'), ('black', 'Black'), ('blue', 'Blue'), ('yellow', 'Yellow')], default='white', max_length=100),
        ),
    ]
