# Generated by Django 2.0 on 2018-07-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0003_auto_20180710_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorsize',
            name='color',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Tag.ProductColor'),
        ),
        migrations.AlterField(
            model_name='productcolorsize',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Tag.ProductSize'),
        ),
    ]
