# Generated by Django 2.0 on 2018-07-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0005_auto_20180710_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcolorsize',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productcolorsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcolorsize',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductColorSize',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
