# Generated by Django 2.0 on 2018-07-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0006_auto_20180710_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='SubType',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('bags', 'Bags'), ('accessories', 'Accessories'), ('clothes', 'Clothes'), ('shirts', 'Shirts'), ('mobiles', 'Mobiles'), ('cameras', 'Cameras'), ('laptop', 'Laptop'), ('tv', 'TV'), ('washingMachines', 'WashingMachines')], max_length=300),
        ),
    ]
