# Generated by Django 2.0 on 2018-07-10 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_Type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=250)),
                ('Address_line_1', models.CharField(max_length=250)),
                ('Address_line_2', models.CharField(blank=True, max_length=250, null=True)),
                ('State', models.CharField(default='kuwait', max_length=250)),
                ('Postal_Code', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billing')),
            ],
        ),
    ]
