# Generated by Django 2.0 on 2018-11-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_Type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=250)),
                ('Address_line_1', models.CharField(max_length=250, verbose_name='Address1')),
                ('Address_line_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address2')),
                ('State', models.CharField(default='kuwait', max_length=250, verbose_name='State')),
                ('Postal_Code', models.CharField(max_length=250, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=250, verbose_name='City')),
                ('ContactNo', models.CharField(max_length=250, verbose_name='Contact Number')),
                ('FullName', models.CharField(default='hossam', max_length=250, verbose_name='Full Name')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billing')),
            ],
        ),
    ]
