# Generated by Django 2.0 on 2018-07-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0002_auto_20180731_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Address_Type',
            field=models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=250, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='address',
            name='Address_line_1',
            field=models.CharField(max_length=250, verbose_name='Address1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='Address_line_2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Address2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='ContactNo',
            field=models.CharField(default=True, max_length=250, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='FullName',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='Postal_Code',
            field=models.CharField(max_length=250, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='State',
            field=models.CharField(default='kuwait', max_length=250, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=250, verbose_name='City'),
        ),
    ]
