# Generated by Django 2.0 on 2018-07-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0003_auto_20180731_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Address_Type',
            field=models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=250),
        ),
    ]
