# Generated by Django 2.0 on 2018-07-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0004_auto_20180731_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ContactNo',
            field=models.CharField(max_length=250, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='FullName',
            field=models.CharField(max_length=250, verbose_name='Full Name'),
        ),
    ]
