# Generated by Django 2.0 on 2018-07-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0006_auto_20180731_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='FullName',
            field=models.CharField(default='hossam', max_length=250, verbose_name='Full Name'),
        ),
    ]
