# Generated by Django 2.0 on 2018-05-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
