# Generated by Django 2.0 on 2018-07-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_auto_20180724_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FirstName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='user',
            name='LastName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LastName'),
        ),
    ]
