# Generated by Django 2.0 on 2018-07-10 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('billing', '0001_initial'),
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=25, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('canceled', 'Canceled')], default='created', max_length=25)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=5.0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('active', models.BooleanField(default=True)),
                ('Billing_Address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Billing_Address', to='Address.Address')),
                ('billing_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.billing')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('shipping_Address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_Address', to='Address.Address')),
            ],
        ),
    ]
