# Generated by Django 2.0 on 2018-07-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('shipped', 'Shipped'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='created', max_length=25),
        ),
    ]
