# Generated by Django 2.0 on 2018-07-15 11:24

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180710_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_file_name),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_file_name),
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_file_name),
        ),
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_file_name),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('red', 'Red'), ('black', 'Black'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('purple', 'Purple')], default='white', max_length=100),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('Extra Small', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Small Medium', 'sm'), ('Large', 'L'), ('Extra Large', 'XL'), ('Double Large', 'XXL'), ('Triple Large', 'XXXL'), ('13 inch', "13 ''"), ('15 inch', "15 ''")], default='Small', max_length=100),
        ),
    ]
